### ISSUE TITLE
Windows 10 exclusive integration

### ISSUE THREAD

**Issue by g-yui** [acidicoala/Koalageddon#1]
https://github.com/acidicoala/Koalageddon/blob/9e2a04bcd4eac009cdd53b6e940891d63ea0e4b0/Common/src/util.cpp#L118

I have just a question since I don't really do much in the way of injection, what would the IsWow64Process2 do for the project were it to be used? As I understand it, it's not used for compatibility, but if it were a question of performance or some other important factor that would help users of Windows 10 something along these lines could potentially be used.

```

#include<iostream>
#include<string>
#include <windows.h>
using namespace std;

int GetOsVersion() // Source for this function is https://svsivan.blogspot.com/2020/07/get-os-version-c.html
{
    int osver = 0.0;

    NTSTATUS(WINAPI * RtlGetVersion)(LPOSVERSIONINFOEXW);

    OSVERSIONINFOEXW osInfo;

    *(FARPROC*)&RtlGetVersion = GetProcAddress(GetModuleHandleA("ntdll"), "RtlGetVersion");

    if (NULL != RtlGetVersion)
    {
        osInfo.dwOSVersionInfoSize = sizeof(osInfo);
        RtlGetVersion(&osInfo);
        osver = osInfo.dwMajorVersion;
    }

    return osver;
   
}

bool util()
{
    int winVersion = GetOsVersion();
    if (winVersion == 10){
        BOOL isWow64 = NULL;
        IsWow64Process2(hProcess, &isWow64);
        return isWow64;
    }
    else {
        BOOL isWow64 = NULL;
        IsWow64Process(hProcess, &isWow64);
        return isWow64;
    }
    
}

```

Lovely project as always, may it bring forth the Koalageddon to overpriced DLC!!!

**Comment by acidicoala** [comment]
`IsWow64Process2` can provide us with more information about the process or host OS. In the end it turned out to be unnecessary and `IsWow64Process` is sufficient. With respect to this project, there will be no difference is using either of them.

P.S. The function signature of `IsWow64Process2` is a little different. Have a look at [documentation](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2).

P.S.S. Even some Windows 10 versions may not have this function available. A more reliable check would be to see if the OS kernel module contains this function. [See the example](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process#examples) MS documentation provides for `IsWow64Process`.

**Comment by g-yui** [comment]
Oh I see, thank you!
