### ISSUE TITLE
-Unrelated- Hooking into KernelAPI calls  -🐨 -

### ISSUE THREAD

**Issue by g-yui** [acidicoala/Koalageddon#4]
Hello koala!
This is completely unrelated to the project but I don't have much of a way to DM for such a thing 😢 

I was wondering how I could hook into certain calls, namely, `GetSystemTime, GetLocalTime, GetSystemTimeAsFileTime, NtQuerySystemTime, GetSystemTimePreciseAsFileTime, GetSystemTimeAdjustment, GetSystemTimeAdjustmentPrecise, GetSystemTimes, RtlGetSystemTimePrecise` , among others.
All in all, just every windows call to give a time value to a program that requests it, what I intend to do is essentially Nirsoft's RunAsDate but open source and more powerful, as it cannot, for instance, spoof the datetime library from Python.

The problem being that I do not have experience using PolyHook2 or any hooking library, and the documentation is just past me, as such I would like to humbly ask for your help with this project, if you accept we can move to discuss this wherever you wish, otherwise you can just close this issue, as I know you have other projects to work on and time is of the essence.

Thank you for your attention and have a good day!

**Comment by acidicoala** [comment]
I personally believe that you might need to get comfortable with some of the basic aspects of C++ before you move on to more advanced ones. In other issue you mentioned that
> I've yet to make a header file myself.

I mean this is like learning how to fly without learning how to walk first.

Nevertheless, if you feel like you are equipped for the job, then there are plenty of tutorials out there, just google `c++ function hooking` in general or `WinAPI function hooking tutorial` in your specific case. [First google search result](https://www.ired.team/offensive-security/code-injection-process-injection/how-to-hook-windows-api-using-c++).

The author of the `polyhook` library has actually written several articles regarding hooking methods which is available [here](https://www.codeproject.com/articles/1100579/polyhook-the-cplusplus-x-x-hooking-library). There are other hooking libraries out there, so you are free to choose any of them. It's just that most of them only support `Detour` hooks, while polyhook 2 supports 8 different types of hooks. From your use case you can either use `Detour`, `IAT`, or `EAT` hooks. Koalageddon itself has couple of examples, although it might be difficult to understand the relevant part because of the presence of other code. [Example with `CreateProcessW`](https://github.com/acidicoala/Koalageddon/blob/d4b3412a5cca93413f29e6ff6d732c2ff7a0ab1d/Unlocker/src/ProcessHooker.cpp#L246).

**Comment by acidicoala** [comment]
I just remembered that in case of WinAPI, hooking doesn't really require hooking libraries.

Normally you need to execute the overwritten instructions if you hook functions, and the logic that handles that can become quite complex, if you are aiming to cover all possible cases. This is what hooking libraries are trying to take care of - correctly executing the overwritten instruction, if you call the original.  But Microsoft has deliberately reserves the first 4 bytes of function prolog with 2 `nop`s (it's `mov edi, edi` actually, which is slightly faster than 2 `nop`s, but still occupies 4 bytes). So you can simply overwrite them with a `jmp` instruction to any address without having to deal with the overwritten instructions, which is what the hooking libraries are made to deal with. And you can safely call the instruction right after the reserved for bytes to execute the original.

Microsoft has reserved those 4 bytes to allow hot-patching security vulnerabilities on machines where rebooting is not possible without preparation. For example you cannot simply reboot a web server since it may bring down one or more websites for quite some time.

**Comment by acidicoala** [comment]
I just remembered that Polyhook 2 has a dead-simple example for a standard Detour hook: https://github.com/stevemk14ebr/PolyHook_2_0/blob/25c88bacc317ae1c371887b5d826f513301ce4e4/ExampleProject/ExampleProject/ExampleProject/ExampleProject.cpp

**Comment by g-yui** [comment]
Thank you :D
